package common

import (
	"github.com/store_server/utils/errors"
)

var (
	//参考: https://docs.google.com/spreadsheets/d/1jKAC7fFpotmWK62o63fb8tqRFPS175-w5au1uxblFJw/edit#gid=0
	//may be can reload from local disk file
	SourceMap = map[int]map[string]interface{}{
		//0: "QQ",
		0: {"name": "JOOX_EDITOR_VIDEO",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		1: {"name": "GD",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		2: {"name": "OSM",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		3: {"name": "GD_TMP",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 0,
				"MM": 0,
			}},
		4: {"name": "GD_MY",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		5: {"name": "BEC_TH",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 1,
				"ZA": 0,
			}},
		6: {"name": "SONY_HK",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 0,
				"MM": 0,
			}},
		7: {"name": "BELIEVE_DIGITAL",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		8: {"name": "GMM",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 1,
				"ZA": 0,
				"MM": 0,
			}},
		9: {"name": "WARNER_TH",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 1,
				"ZA": 0,
				"MM": 0,
			}},
		10: {"name": "UNIVERSAL_TH",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 1,
				"ZA": 0,
				"MM": 0,
			}},
		11: {"name": "SOLUTION_ONE_TH",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 1,
				"ZA": 0,
				"MM": 0,
			}},
		12: {"name": "MOINDY_TH",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 1,
				"ZA": 0,
				"MM": 0,
			}},
		13: {"name": "PHONORIGHT_TH",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 1,
				"ZA": 0,
				"MM": 0,
			}},
		14: {"name": "SANOOK_MUSIC_TH",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 1,
				"ZA": 0,
				"MM": 0,
			}},
		15: {"name": "UMG_HK_DDEX",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		16: {"name": "RS_TH",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 1,
				"ZA": 0,
				"MM": 0,
			}},
		17: {"name": "WARNER_TH_DDEX",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		18: {"name": "SONY_DDEX",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		19: {"name": "THMT",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 0,
				"MM": 1,
			}},
		20: {"name": "QQVIDEO",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		21: {"name": "SM_TRUE",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 1,
				"ZA": 0,
				"MM": 0,
			}},
		22: {"name": "TURNUPMUSICSA",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 1,
				"MM": 0,
			}},
		23: {"name": "JOOX_EDITOR_AUDIO",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		24: {"name": "LEGACY_MM",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 0,
				"MM": 1,
			}},
		25: {"name": "BLINK_MM",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 0,
				"MM": 1,
			}},
		26: {"name": "9NIGHT_MM",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 0,
				"MM": 1,
			}},
		27: {"name": "COLESKE",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 1,
				"MM": 0,
			}},
		28: {"name": "THE ORCHARD",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 0,
				"MM": 0,
			}},
		29: {"name": "AFRICORI",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 1,
				"MM": 0,
			}},
		30: {"name": "INgrooves",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		31: {"name": "Alpha Pup",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		32: {"name": "Explore Music",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		33: {"name": "April",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 0,
				"MM": 1,
			}},
		34: {"name": "Love Da Records",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		35: {"name": "TUM SA",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 1,
				"MM": 0,
			}},
		36: {"name": "MMN",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 0,
				"MM": 1,
			}},
		37: {"name": "BUBBLEWRAP",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		38: {"name": "StreetVoice",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		39: {"name": "EMPIRE",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		40: {"name": "FUGA",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		41: {"name": "Genie Music",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		42: {"name": "IONEKOREA",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		43: {"name": "Golden Dynamic",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		44: {"name": "CI Support Recordings",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		45: {"name": "TwentyTwo",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		46: {"name": "JOOX-EXM1",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		47: {"name": "Musica Studios",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 0,
				"MM": 0,
			}},
		48: {"name": "CCA",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 1,
				"MM": 0,
			}},
		49: {"name": "MAD",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 1,
				"MM": 0,
			}},
		50: {"name": "The Sun Music",
			"copyright": map[string]int{
				"HK": 0,
				"MY": 0,
				"ID": 0,
				"TH": 0,
				"ZA": 0,
				"MM": 1,
			}},
		51: {"name": "KKFARM",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 0,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		52: {"name": "Ditto",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		53: {"name": "JOOX - EXM2",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		54: {"name": "Tunecore",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		55: {"name": "Horus",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		56: {"name": "Trinity Optima",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
		57: {"name": "E-Motion",
			"copyright": map[string]int{
				"HK": 1,
				"MY": 1,
				"ID": 1,
				"TH": 1,
				"ZA": 1,
				"MM": 1,
			}},
	}
)

func GetSourcesById(id int, onlyName bool) (interface{}, error) {
	if info, ok := SourceMap[id]; ok {
		if onlyName {
			return info["name"], nil
		} else {
			return info, nil
		}
	}
	return nil, errors.New("source not found")
}

func GetSourcesByIds(ids []int, onlyName bool) (interface{}, error) {
	var infos []interface{}
	for _, id := range ids {
		if info, ok := SourceMap[id]; ok {
			if onlyName {
				infos = append(infos, map[int]interface{}{id: info["name"]})
			} else {
				infos = append(infos, map[int]interface{}{id: info})
			}
		} else {
			return nil, errors.New("source not found")
		}
	}
	return infos, nil
}
